# Generated by Django 3.0.2 on 2020-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceFeaturesSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.TextField()),
                ('selected', models.TextField()),
                ('num_hints', models.IntegerField()),
            ],
        ),
    ]
